---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/unit}

inputs:
- name: concourse
- name: version
- name: latest-version
- name: latest-of-same-major-version

outputs:
- name: tags

run:
  path: concourse/ci/tasks/scripts/docker-semver-tags
